apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    name: {{ .Values.ingress.labels.name }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}

{{- if .Values.ingress.tls }}
  rules:
{{ toYaml .Values.ingress.rules | indent 4 }}
{{- end }}
