apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    name: {{ Values.metadata.labels.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.spec.port }}
