{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    name: {{ .Values.service.name }}
  type: {{ .Values.service.typeport }}
  ports:
    - port: {{ .Values.service.serviceport }}
      targetPort: {{ .Values.deployment.containerport }}
{{- end }}