metadata:
  namespace: staging
  labels:
    name: koala-listing-web-staging

service: 
  name: koala-listing-web-services-staging
  port: 3000

image:
    repository: koalapro/koala_listing_web
    tag: staging
    pullPolicy: Always
    
spec:
  replicas: 1
  port: 3000
  nodeSelector: staging
  
  # containers: 
  #   readinessProbe: 
  #     httpGet:
  #       path: /ping
  #       port: 7723
  #     initialDelaySeconds: 15
  #     periodSeconds: 30
  #     timeoutSeconds: 10
  #   livenessProbe:
  #     httpGet:
  #       path: /ping
  #       port: 7723
  #     initialDelaySeconds: 15
  #     periodSeconds: 30
  #     timeoutSeconds: 10

  #   resources: 
  #     limits:
  #       cpu: 400m
  #       memory: 500Mi
  #     requests:
  #       cpu: 200m
  #       memory: 256Mi

    #env: []
      # Uncomment this section to add container env variables
      # - name: DB_HOST
      #   value: '10.11.0.32'
      # - name: DB_password
      #   value: 'xxxxxxx'

  # volumes:
  #   - name: tz-config
  #     hostPath:
  #       path: /usr/share/zoneinfo/Asia/Jakarta

configmap: [] 

ingress:
  name: koala-listing-web-ingress
  labels:
    name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: 
    - secretName: koala-pro-id-tls
  rules:
    - host: listing.koala-pro.id
      http:
        paths:
          - path: /
            backend:
              serviceName: koala-listing-web-services-staging
              servicePort: 3000

#hpa: []
  # enabled: false
  # minReplicas: 1
  # maxReplicas: 2
  # metrics:
  #   cpu:
  #     targetAverageUtilization: 70
  #   # memory:
  #   #   targetAverageUtilization: 70