  replicaCount: 1

  nodeSelector:

  namespace: staging

  metadata:
    deployment: koala-listing-web-staging
    service: koala-listing-web-services-staging
    ingress: koala-listing-web-ingress
    hpa: hpa-koala-listing-web-production 

  image:
    repository: koalapro/koala_listing_web
    tag: staging
    pullPolicy: Always

  port: 
    type: ClusterIP
    containerport: 3000
    serviceport: 3000

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  ingress:
    enabled: true
    labels: nginx-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: koala-pro-id-tls
        hosts:
          - listing.koala-pro.id
    rules:
      - host: listing.koala-pro.id
        http:
          paths:
            - path: /
              backend:
                serviceName: koala-listing-web-services-staging
                servicePort: 3000
    
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    metrics:
      cpu:
        targetAverageUtilization: 60
      # memory:
      #   targetAverageUtilization: 70
